### PR TITLE
Release/v45.1.0

### PR DESCRIPTION
**Pull request by gingerbenw**
## v45.1.0 (2022-07-28)

This release adds support for sourcemap uploads when using EAS Build

### Added

- Added new `@bugsnag/plugin-expo-eas-sourcemaps` plugin [#40](https://github.com/bugsnag/bugsnag-expo/pull/40)
- Updated CLI tool to automate installation of sourcemap plugin [#40](https://github.com/bugsnag/bugsnag-expo/pull/40)

### CODE REVIEW

**Review by tomlongridge — APPROVED** [review]

**Comment by giaset** [comment]
This is awesome, thanks guys! Ant chance we can get this update published to npm?

**Comment by thorbenprimke** [comment]
Yes, thanks so much for getting the sourcemap upload integrated/working with EAS. 

Please publish to npm! thanks!

**Comment by gingerbenw** [comment]
Hi @giaset, @thorbenprimke, we have just released v45.1.0 of our CLI tool and new source map upload plugin, there are no changes to the base expo package. Please see our documentation for [showing full stacktraces](https://docs.bugsnag.com/platforms/react-native/expo/#showing-full-stacktraces), or our [manual setup guide](https://docs.bugsnag.com/platforms/react-native/expo/manual-setup/#release-tracking-and-source-map-upload). Please note that the automatic symbol uploads are currently only available for expo v45. hope this helps!

**Comment by thorbenprimke** [comment]
@gingerbenw - Thanks for the reply. I didn't realize that there are multiple packages. I got it integrated successfully. It's good to see readable stacktraces! 

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2F3oEjHWXddcCOGZNmFO%2Fgiphy.gif&token=thanks" data-gitmeme-token="thanks"></a>

Our project is in a monorepo. There are two places where you reference the node_modules folder that I had to tweak. I'll file an issue to make it dynamic.

**Comment by gingerbenw** [comment]
sounds good! thanks @thorbenprimke 👍🏻

**Pull request merged**
